/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraiteurRouteImport } from './routes/traiteur'
import { Route as PatisseriesRouteImport } from './routes/patisseries'
import { Route as HistoireRouteImport } from './routes/histoire'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TraiteurRoute = TraiteurRouteImport.update({
  id: '/traiteur',
  path: '/traiteur',
  getParentRoute: () => rootRouteImport,
} as any)
const PatisseriesRoute = PatisseriesRouteImport.update({
  id: '/patisseries',
  path: '/patisseries',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoireRoute = HistoireRouteImport.update({
  id: '/histoire',
  path: '/histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/histoire': typeof HistoireRoute
  '/patisseries': typeof PatisseriesRoute
  '/traiteur': typeof TraiteurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/histoire': typeof HistoireRoute
  '/patisseries': typeof PatisseriesRoute
  '/traiteur': typeof TraiteurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/histoire': typeof HistoireRoute
  '/patisseries': typeof PatisseriesRoute
  '/traiteur': typeof TraiteurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/histoire' | '/patisseries' | '/traiteur'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/histoire' | '/patisseries' | '/traiteur'
  id: '__root__' | '/' | '/contact' | '/histoire' | '/patisseries' | '/traiteur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HistoireRoute: typeof HistoireRoute
  PatisseriesRoute: typeof PatisseriesRoute
  TraiteurRoute: typeof TraiteurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traiteur': {
      id: '/traiteur'
      path: '/traiteur'
      fullPath: '/traiteur'
      preLoaderRoute: typeof TraiteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patisseries': {
      id: '/patisseries'
      path: '/patisseries'
      fullPath: '/patisseries'
      preLoaderRoute: typeof PatisseriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histoire': {
      id: '/histoire'
      path: '/histoire'
      fullPath: '/histoire'
      preLoaderRoute: typeof HistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HistoireRoute: HistoireRoute,
  PatisseriesRoute: PatisseriesRoute,
  TraiteurRoute: TraiteurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
